### ISSUE TITLE
Not working for PowerShell

### ISSUE THREAD

**Issue by jdhitsolutions** [tariky/easy-snippet-maker#2]
I can get snippets to work as expected for a plain text file. But when I try the same thing with a PowerShell language snippet, I get all of the prompts but nothing gets written to the powershell.json file. I have other snippets in the file so I know it works. No errors and no results.  Running VS Code 1.10.2

**Comment by jdhitsolutions** [comment]
Think I found the problem. The default PowerShell.json file includes a large block comment explaining how to use it. Manually entering snippets still works. But when your extension is running I think it is failing with an unsurfaced error. I removed the block comment and now the extension works as expected.

**Comment by tariky** [comment]
It is fixed in version 0.0.4
