### ISSUE TITLE
Please help fix bug!

### ISSUE THREAD

**Issue by snoopy83101** [tariky/easy-snippet-maker#4]
Easy Snippet Maker is so good! 
When  JavaScript snippet  has annotated “//“ 
then can't add it

Sorry, I don't speak English well

Can you fix it?

@tariky

**Comment by tariky** [comment]
I don't have any free time for now. But in like 7 days I will try to fix it.

**Comment by tariky** [comment]
@snoopy83101 Fixed. :)
